# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b1a1058d7bb7fbef7f544fbbcb6c4e11272c8408a6de1d4ad47f5cd237759bc1782738f9d2381d9247ab54420c5b3cea3f270d5c634a6e9d4ad2a114ae6162a

test:
  secret_key_base: a1902df92f09c1681d19682b6efa0a82aba1451ed33a09e1fdd909cc0425b80902ee37caacc4e511dcbe16f9df40a731a19c859ab10b87e15b0f5e1a595f00c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
